apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hackday-pipeline
  labels:
    origin-branch: BRANCH_NAME
description: hackday pipeline
serialPipeline:
  stages:
    - targetId: run-hackday-dev
      profiles: [dev]
      strategy:
        standard:
          verify: true
    - targetId: run-hackday-prod
      profiles: [prod]
      strategy:
        canary:
          runtimeConfig:
            cloudRun:
              automaticTrafficControl: true
          customCanaryDeployment:
            phaseConfigs:
              - phaseId: smoke
                percentage: 0
                profiles: [prod]
                verify: true
              - phaseId: canary-10
                percentage: 10
                profiles: [prod]
                verify: false
              - phaseId: canary-50
                percentage: 50
                profiles: [prod]
                verify: false
              - phaseId: stable
                percentage: 100
                profiles: [prod]
                verify: false
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-hackday-dev
description: Cloud Run development service
run:
  location: projects/decomp-phase-2-hack-day/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-hackday-prod
description: Cloud Run production service
run:
  location: projects/decomp-phase-2-hack-day/locations/us-central1
