apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: yaml-pipeline
description: yaml-pipeline
serialPipeline:
  stages:
  - targetId: target
    profiles:
    - test
    strategy:
     standard:
       verify: true
  
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: target
run:
  location: projects/dvplt-hackathon-sandbox/locations/us-east1