steps:
- name: 'docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/decomp-phase-2-hack-day/hack-day-docker-central/hackathon:v1.0', '.' ]

images:
  - 'us-central1-docker.pkg.dev/decomp-phase-2-hack-day/hack-day-docker-central/hackathon:v1.0'