steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  script: |
    #!/bin/bash
    BRANCH_HASH="$(echo $_DEPLOY_BRANCH | sha256sum | head -c8)"
    
    sed -i "s/DEPLOY_BRANCH_HASH/$BRANCH_HASH/g" cicd/cloud-run-verify.yaml
    sed -i "s/DEPLOY_BRANCH_NAME/$_DEPLOY_BRANCH/g" cicd/cloud-run-verify.yaml
    sed -i "s/DEPLOY_SHA/$_DEPLOY_SHA/g" cicd/cloud-run-verify.yaml
    
    gcloud run jobs replace \
      --region=us-central1 \
      cicd/cloud-run-verify.yaml
    
    gcloud run jobs execute \
      --region=us-central1 \
      hackday-verify-$BRANCH_HASH

substitutions:
  _CLOUD_RUN_PROJECT: 'decomp-phase-2-hack-day'
  _CLOUD_RUN_REVISION: ''
  _CLOUD_RUN_SERVICE: 'hackday-dev'
  _DEPLOY_SHA: ''
  _DEPLOY_BRANCH: 'master'

options:
  automapSubstitutions: true
