steps:
# NPM install and Test
- name: "gcr.io/cloud-builders/npm"
  args: ["install"]
- name: "gcr.io/cloud-builders/npm"
  args: ["run", "test"]
  id: test

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE_NAME', '.']
  id: 'build'
  waitFor: ['test']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_IMAGE_NAME']
  waitFor: ['build']

# Build the test image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'e2e'
  args: ['build', '-t', '$_VERIFY_IMAGE_NAME', '.']
  id: 'build-e2e'
  waitFor: ['test']
# Push the test image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  dir: 'e2e'
  args: ['push', '$_VERIFY_IMAGE_NAME']
  waitFor: ['build-e2e']

# Deploy using cloud deploy to cloud run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  env:
  - 'IMAGE_NAME=$_IMAGE_NAME'
  - 'VERIFY_IMAGE_NAME=$_VERIFY_IMAGE_NAME'
  script: |
    #!/bin/bash -e
    BRANCH_HASH="$(echo ${BRANCH_NAME} | sha256sum | head -c8)"

    sed -i "s|\$BRANCH_HASH|${BRANCH_HASH}|g" clouddeploy.yaml
    sed -i "s|\$BRANCH_NAME|${BRANCH_NAME}|g" clouddeploy.yaml
    
    sed -i "s|\$BRANCH_HASH|${BRANCH_HASH}|g" skaffold.yaml
    sed -i "s|\$BRANCH_NAME|${BRANCH_NAME}|g" skaffold.yaml
    sed -i "s|\$VERIFY_IMAGE_NAME|${VERIFY_IMAGE_NAME}|g" skaffold.yaml
    sed -i "s|\$DEPLOY_BRANCH|${BRANCH_NAME}|g" skaffold.yaml
    sed -i "s|\$DEPLOY_SHA|${REVISION_ID}|g" skaffold.yaml

    gcloud deploy apply \
      --file=clouddeploy.yaml \
      --region=${LOCATION} \
      --project=${PROJECT_ID}

    gcloud deploy releases create release-${SHORT_SHA} \
      --region=${LOCATION} \
      --project=${PROJECT_ID} \
      --delivery-pipeline=hackday-pipeline \
      --images=hackday-image=${IMAGE_NAME} \
      --deploy-parameters=deploy_branch=${BRANCH_NAME},deploy_sha=${SHORT_SHA}

substitutions:
  _IMAGE_NAME: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/hack-day-docker-central/hackathon:${SHORT_SHA}'
  _VERIFY_IMAGE_NAME: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/hack-day-docker-central/hackathon-verify:${SHORT_SHA}'

options:
  pool:
    name: 'projects/decomp-phase-2-hack-day/locations/us-central1/workerPools/hackday-pool'
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
  automapSubstitutions: true
