options:
  logging: CLOUD_LOGGING_ONLY
steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - '${IMAGE_LOCATION}:$SHORT_SHA'
  - '.'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'deploy'
  - 'releases'
  - 'create'
  - 'penguin-$$DATE-$$TIME'
  - '--images'
  - 'image1=${IMAGE_LOCATION}:$SHORT_SHA'
  - '--region'
  - 'us-east1'
  - '--delivery-pipeline=yaml-pipeline'
images:
- '${IMAGE_LOCATION}:$SHORT_SHA'
substitutions:
  IMAGE_LOCATION: us-east1-docker.pkg.dev/dvplt-hackathon-sandbox/hackathon-docker/hackathon-app