steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_IMAGE_NAME', '.']
  id: 'build'

# Build dev image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'hackday-dev', '--target', 'dev', '.']
  id: 'build-dev'
  waitFor: ['build']

# Run tests
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'hackday-dev', 'npm', 'run', 'test']
  id: 'test'
  waitFor: ['build-dev']

# Build the test image
- name: 'gcr.io/cloud-builders/docker'
  dir: 'e2e'
  args: ['build', '-t', '$_VERIFY_IMAGE_NAME', '.']
  id: 'build-e2e'

# Deploy using cloud deploy to cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  env:
  - 'IMAGE_NAME=$_IMAGE_NAME'
  - 'VERIFY_IMAGE_NAME=$_VERIFY_IMAGE_NAME'
  script: |
    #!/bin/bash -e
    BRANCH_HASH="$(echo ${BRANCH_NAME} | sha256sum | head -c8)"

    sed -i "s|\$BRANCH_HASH|${BRANCH_HASH}|g" clouddeploy.yaml
    sed -i "s|\$BRANCH_NAME|${BRANCH_NAME}|g" clouddeploy.yaml
    
    sed -i "s|\$BRANCH_HASH|${BRANCH_HASH}|g" skaffold.yaml
    sed -i "s|\$BRANCH_NAME|${BRANCH_NAME}|g" skaffold.yaml
    sed -i "s|\$VERIFY_IMAGE_NAME|${VERIFY_IMAGE_NAME}|g" skaffold.yaml
    sed -i "s|\$DEPLOY_BRANCH|${BRANCH_NAME}|g" skaffold.yaml
    sed -i "s|\$DEPLOY_SHA|${REVISION_ID}|g" skaffold.yaml

    gcloud deploy apply \
      --file=clouddeploy.yaml \
      --region=${LOCATION} \
      --project=${PROJECT_ID}

    gcloud deploy releases create release-${SHORT_SHA} \
      --region=${LOCATION} \
      --project=${PROJECT_ID} \
      --delivery-pipeline=hackday-pipeline \
      --images=hackday-image=${IMAGE_NAME} \
      --deploy-parameters=deploy_branch=${BRANCH_NAME},deploy_sha=${SHORT_SHA}

substitutions:
  _IMAGE_NAME: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/hackathon-docker/hackathon:${SHORT_SHA}'
  _VERIFY_IMAGE_NAME: '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/hackathon-docker/hackathon-verify:${SHORT_SHA}'

images:
- '${_IMAGE_NAME}'
- '${_VERIFY_IMAGE_NAME}'

options:
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true
  automapSubstitutions: true
