apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: hackday-pipeline
description: hackday pipeline
serialPipeline:
  stages:
    - targetId: run-hackday-dev
      profiles: [dev]
      strategy:
        standard:
          verify: true
    - targetId: run-hackday-prod
      profiles: [prod]
      strategy:
        standard:
          verify: false
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-hackday-dev
description: Cloud Run development service
run:
  location: projects/decomp-phase-2-hack-day/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: run-hackday-prod
description: Cloud Run production service
run:
  location: projects/decomp-phase-2-hack-day/locations/us-central1
