apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-hackday-dev
spec:
  template:
    spec:
      containers:
        - image: heackday-image
          ports:
            - name: http1
              containerPort: 3000
          env:
            - name: FOO
              value: dev foo
            - name: BAR
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: val-secret
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000

