apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: hackday-cloud-deploy
profiles:
  - name: dev
    manifests:
      rawYaml:
        - run-dev.yaml
  - name: prod
    manifests:
      rawYaml:
        - run-prod.yaml

deploy:
  cloudrun: {}

verify:
  - name: hackday-verify-image
    container:
      name: hackday-verify-image
      image: hackday-verify-image
      command: ['run']

