apiVersion: skaffold/v4beta6
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  local: {}
manifests:
  rawYaml:
    - /workspace/source/run-target-2.yaml
deploy:
  cloudrun: {}
  logs:
    prefix: container
