apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: vue-ssr-hackathon
profiles:
  - name: local
    build:
      artifacts:
        - image: hackday-dev-image
          sync:
            manual:
              - src: src/**/*
                dest: /app
              - src: public/**/*
                dest: /app
              - src: html/**/*
                dest: /app
          docker:
            dockerfile: Dockerfile
            target: dev
    test:
      - image: hackday-dev-image
        custom:
          - command: npm run test
    manifests:
      rawYaml:
        - cicd/local.yaml
    portForward:
      - resourceType: deployment
        resourceName: hackday
        port: 3000
      - resourceType: deployment
        resourceName: hackday
        port: 9229
  - name: dev
    deploy:
      cloudrun: {}
    verify:
      - name: hackday-verify
        container:
          name: hackday-verify
          image: gcr.io/google.com/cloudsdktool/cloud-sdk
          command: ['bash']
          args:
            - '-exc'
            - |-
              gcloud beta run jobs update hackday-verify-$BRANCH_HASH \
                --wait \
                --image=$VERIFY_IMAGE_NAME \
                --args=run \
                --set-env-vars=NO_COLOR=1,ELECTRON_ENABLE_LOGGING=1,CYPRESS_BASE_URL=$CLOUD_RUN_SERVICE_URLS \
                --cpu=1000m \
                --memory=1Gi \
                --max-retries=0 \
                --tasks=1 \
                --parallelism=1 \
                --labels=origin-branch=$BRANCH_NAME \
                --vpc-egress=private-ranges-only \
                --network=hackday-vpc \
                --subnetwork=hackday-subnet-central
            # - 'gcloud builds triggers run hackday-verify --region=us-central1 --sha=$DEPLOY_SHA --substitutions _CLOUD_RUN_PROJECT=$CLOUD_RUN_PROJECT,_CLOUD_RUN_SERVICE=$CLOUD_RUN_SERVICE,_CLOUD_RUN_REVISION=$CLOUD_RUN_REVISION,_CLOUD_RUN_SERVICE_URLS=$CLOUD_RUN_SERVICE_URLS,_DEPLOY_BRANCH=$DEPLOY_BRANCH'
    manifests:
      rawYaml:
        - cicd/cloud-run-dev.yaml
  - name: prod
    deploy:
      cloudrun: {}
    verify:
      - name: hackday-verify-image
        container:
          name: hackday-verify-image
          image: hackday-verify-image
          args: [ 'run' ]
      - name: ubuntu
        container:
          name: ubuntu
          image: ubuntu
          args: [ 'env' ]
    manifests:
      rawYaml:
        - cicd/cloud-run-prod.yaml
