apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-hackday-prod
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
spec:
  template:
    spec:
      containers:
        - image: hackday-image
          ports:
            - name: http1
              containerPort: 3000
          env:
            - name: FOO
              value: prod foo
            - name: BAR
              valueFrom:
                secretKeyRef:
                  key: latest
                  name: val-secret2
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 3000
